---
title: "Week #2"
author: "Adrian Correndo & Josefina Lacasa"
format:
  html:
    fontsize: 0.8em
    linestretch: 1
---

# Introduction to Bayesian Stats

This article is intended to provide a brief introduction to key concepts about Bayesian theory and differences with the traditional Frequentist approach:

::: callout-important
Neither of both, Frequentist or Bayesian, are always the most suitable solution for your analysis. However....😉
:::

For this reason, today we are going to discuss and compare both approaches.

Let's watch some short videos about it

## 1. Frequentism vs Bayesianism

::: {align="center"}
<iframe width="560" height="315" src="https://www.youtube.com/embed/tsuJM_bHSgA" frameborder="0" allowfullscreen>

</iframe>
:::

What do you think?

-   Open discussion....

------------------------------------------------------------------------

## 2. Main Differences

Perhaps, the main disagreement between Frequentism and Bayesianism is about the TRUTH.

The Frequentism vision is heavily rooted on the actual existence of the TRUTH. Every time we estimate a model's parameter, we expect to approximate to a true value. It is named "frequentism" because it is based on the frequency of repeated events.

For example, if we want to assess the probability of getting a #6 when rolling a dice, Frequentism says that ***"If we roll a dice close to infinite times, the proportion of #6 out of the total number of rolls will approach 16.7% (the theoretical probability)"***. Thus, Frequentism makes inference conditional to an ideal, "theoretical" condition of repeating the same experiment infinite times. In other words, conclusions rely on events we have not observed.

The Bayesian approach instead, DOES NOT assume the existence of the TRUTH. In contrast, it is based on PROBABILITIES & BELIEFS.

PROBABILITIES: For the Bayesian vision, everything is a matter of probability. Any fact or result about an "estimate" could range from extremely unlikely to extremely likely. However, anything is considered completely true or false.

BELIEFS: here is probably the most important point of the Bayesian vision. Bayesian models allow to introduce (and update) prior knowledge on a topic, introducing our own certainty or uncertainty about events. EVEN IF WE DON'T KNOW ANYTHING about it (spoiler alter: uninformative prior!).

Bayesianism considers probability as an expression of the degree of certainty (or uncertainty).

Following the same example with the dice roll, Bayesian interpretation says that ***"we are, a priori, 16.7% certain we are going to get a #6"***. The, Bayesianism makes inference conditional to the data we observed. We basically test the likelihood of a prior hypothesis being true given the observed data, and we generate a new "likelihood" of updated hypothesis being true given the observed data.

And now, to compare previous beliefs (prior) to updated knowledge (posterior) we can introduce the concept of Bayes Factor, which is a ratio between to candidate statistical models represented by marginal likelihood to measure the support for one model over the other. For example, if we have 0.167 as a prior belief of obtaining a #6, and our updated likelihood (after combining with observed data) results 0.334:

$$
Bayes Factor = \frac{0.334}{0.167} = 2
$$

Thus, our updated hypothesis is twice as likely to be true than our prior hypothesis given the observed data.

Therefore, when we analyze our data:

a.  Frequentism assumes models being fixed and our data random (maximum likelihood, conditional to theoretical events).

b.  Bayesian assumes that models can vary around our data (conditional to observed data)

::: callout-tip
For simple models, however, the two approaches would be practically indistinguishable...

HINT: think about uninformative prior knowledge!
:::

::: callout-note
The structure of the Bayesian theory is similar to the Human Logic process:

\(i\) we have some data,

\(ii\) we have beliefs about the underlying process,

\(iii\) combining both, we can update our beliefs.
:::

## 3. Bayes Theorem

$$ P(A_{true} | B)  = \frac{P(B|A_{true}) * P(A_{true})}{P(B)}$$ $$ Posterior  = \frac{Likelihood * Prior}{Evidence}$$

### Bayes' Rule Video

::: {align="center"}
<iframe width="560" height="315" src="https://www.youtube.com/embed/HZGCoVF3YvM" frameborder="0" allowfullscreen>

</iframe>
:::

## 4. The Priors

Priors are basically a formalization of our believes in a form of a mathematical function describing a "distribution". First, it depends on the nature of the variable of interest, which could be "discrete" or "continuous". Second, it depends on what we know (or not) about the process of interest...

## 5. Credible vs. Confidence intervals

There is a very important difference between Frequentism and Bayesianism in terms of error interpretation. Let's say we estimate 95% confidence and credible intervals for $\theta$:

-   **Confidence intervals (Frequentist)**: *"If we repeat the experiment infinite times, 95% of the estimated confidence intervals will contain the true value of* $\theta$ *(based on repeated measurements)"*. Note that since $\theta$ is fixed, it can only be within or outside the interval.

-   **Credible intervals (Bayesian)**: In contrast, Bayesianism has a "literal" interpretation of the error saying, \*"there is a probability of 95% that the parameter\* $\theta$ *lies within this credible interval".* This is a range of probable values. Note:"Given that the prior is correct"...\

## 6. Useful Resources

### Introductory theory:

[Bayesian Models: A Statistical Primer for Ecologists. Hobbs and Hooten](https://www.amazon.com/Bayesian-Models-Statistical-Primer-Ecologists/dp/0691159289/ref=sr_1_1?crid=1VQO8V1SDDIDA&keywords=hooten+hobbs&qid=1662992043&sprefix=hooten+hobbs%2Caps%2C84&sr=8-1)\
[Bringing Bayesian Models to Life. Hooten and Hefley](https://www.amazon.com/Bringing-Bayesian-Chapman-Environmental-Statistics/dp/0367198487/ref=sr_1_1?crid=1UURRINAB9C1X&keywords=bringing+bayesian+models+to+life&qid=1662992123&sprefix=bringing+bayesian+models+to+life%2Caps%2C80&sr=8-1&ufe=app_do%3Aamzn1.fos.006c50ae-5d4c-4777-9bc0-4513d670b6bc)

Not from biological sciences but still very good:\
[Statistical Rethinking. McElreath](https://civil.colorado.edu/~balajir/CVEN6833/bayes-resources/RM-StatRethink-Bayes.pdf)

On Bayesian workflow/philosophy:\
[Bayesian workflow](https://arxiv.org/abs/2011.01808)\
[Scientific Reasoning: The Bayesian Approach. Howson and Urbach](https://www.amazon.com/Scientific-Reasoning-Bayesian-Colin-Howson/dp/081269578X)

### Advanced theory:

[Bayesian Data Analysis 3](https://www.amazon.com/Bayesian-Analysis-Chapman-Statistical-Science/dp/1439840954/ref=sr_1_1?keywords=bayesian+data+analysis+3rd+edition&qid=1662991976&sprefix=bayesian+data+analysis+%2Caps%2C97&sr=8-1)

### Agronomy papers:

[Makowski et al., 2020](https://doi.org/10.1016/j.eja.2020.126076)

### Miscellaneous:

Blog: [Statistical Modeling, Causal Inference, and Social Science. Gelman et al.](https://statmodeling.stat.columbia.edu/)\
Podcast: [Learning Bayesian Statistics](https://open.spotify.com/show/7HYN0pLjob4d8RiwKTvLUa?si=57a30c99d436491a)
