---
title: "Statasaurus' Homepage"
format:
  html:
    fontsize: 1.25em
---

Welcome to the 🍂 Fall 2022 Season 🍂 of Statasaurus!

*History*

*Statasaurus* (a.k.a. Stats-Hub) is a series of encounters designed to share, discuss, learn, and use applied stats and computer programming for agricultural research. It was born in late Fall 2018 from the idea of several lab mates (*Adrian Correndo, Santiago Tamagno, Javier Fernande*z, and *Luiz Moro Rosso*) with the support of their advisor (Dr. Ciampitti) at the KSU Crops team (now [CiampittiLab](https://ciampittilab.wixsite.com/ciampitti-lab)).

*Statasaurus* was conceived with the main goal sharing knowledge about data analysis using R software. By that time, we were mostly using excel for data wrangling, GraphPad Prism for plots, barely used R script files, no Rmarkdown for reports, and no version control. We didn't even know how to create an \*.Rproj file. Rapidly, the entire team adopted the idea and the rest is known history. Over the years, many graduate students, visiting scholars, and postdocs have been sharing their coding and stats knowledge (and doubts) allowing the team to exponentially grow in terms of data analytics skills. Nowadays, we are proudly using these meetings exclusively for advanced programming topics. Welcome to the team!

*General Rules*

::: callout-important
The #1 and most important rule is: ***exchange!*** *When you ask for a topic, you also try to offer another topic in exchange*.

The willing to contribute is of central importance cause we all have duties to take care about. Therefore, self-volunteers are crucial and deeply appreciated.
:::

::: callout-tip
*The meetings are not lectures. Nobody's bringing the truth! We are all learning, so we foster the discussion among members.*
:::

::: callout-note
It is expected that members have:

i\. the latest version of [RStudio](https://www.rstudio.com/products/rstudio/download/) installed.

ii\. an active [GitHub](https://githu.com) account, and...

iii\. training on the basics of data analysis using R.
:::
